var BookmarkConstants = {
  ALL_BOOKMARKS_RECEIVED: "ALL_BOOKMARKS_RECEIVED",
  SINGLE_BOOKMARK_RECEIVED: "SINGLE_BOOKMARK_RECEIVED",
  BOOKMARK_DELETED: "BOOKMARK_DELETED"
};

module.exports = BookmarkConstants;
